Коммит с тестовым проектом
skbkontur/Selone pull request #4
Opened 2021-03-17 16:12 UTC by Ant-VAV

2021-03-24 07:51 UTC, slawwan requested changes

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/typings/retail-ui/components/ComboBoxOld/ComboBoxOld.d.ts
> +export interface ComboBoxOldProps<T> {
думаю надо будет перейти на последнюю версию либы контролов и кстати не помню чтобы в тестовом проекте испоьлзовался комбобокс

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/typings/retail-ui/components/Checkbox/Checkbox.d.ts
> +export interface CheckboxProps {
это тоже пережитки прошлого, в новой версии либы контролов этобудет не нужно

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/typings/render-pdf/index.d.ts
> +import * as React from 'react';
это про pdf-js - копипаста из эврики, надо бы выпилить

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/typings/react-ui-validations/index.d.ts
> +﻿import * as React from "react";
в нвой версии либы валидаций типы из коробки

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/src/Common/Types/Types.ts
> +export type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>;
надо будет обновить тайпскрипт, там `Omit` есть из коробки
и надо будет проанализировать зачем нужен `Diff` - может быть и его выпилить

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/src/Common/Types/Automatic.ts
> +﻿interface Automatic<T> {
похоже на ненжную копипасту из эврики

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/src/Common/Types/Period.ts
> +export default class Period {
убедиться бы что это используется

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/src/Common/Controls/DateInput.tsx
> +//TODO (byTimo) перевести DatePicker на нормальную версию
тут надо обновлять либу контролов да и ValidationWrapperV1  отсюда выпиливать, но вероятно в проекте нет использований контрола вввода даты и его вообще выпилить бы отсюда

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/website-react/src/Common/Controls/CurrencyInput/CurrencyInput.tsx
> +export default class CurrencyInput extends React.Component<CurrencyInputProps, CurrencyInputState> {
пережитки прошлого, в новой либе контролов сть такой контрол

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/readme.md
> +## Неявные ошибки
наверное этот подраздел можно выпилить отсюда

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/readme.md
> +## Упрощение отладки
наверное этот подраздел можно выпилить отсюда

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/ExampleProject/Magic/ChromeDriverFactory.cs
> +                    var chromeDriverService = CreateChromeDriverService();
обсуждали, что сюда надо вернуть магию по фиксированию версии хрома в реестре, чтобы он не обновлялся

2021-03-24 07:51 UTC, slawwan commented on Examples/TestProject/ExampleProject/Magic/ChromeDriverFactory.cs
> +        private static readonly string Path = System.IO.Path.GetFullPath(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", ".."));
обсуждали, что выделим под хром и драйвер отдельнуюб папку, анпрмиер browser и добавим ее в .gitignore

2021-04-19 17:13 UTC, slawwan requested changes

2021-04-19 17:13 UTC, slawwan commented on Examples/TestProject/readme.md
> +Работа проекта проверялась на фрейморке версии 4.7.
`фрейморке версии 4.7` -> `.NET Framework 4.7`

2021-04-20 06:38 UTC, Ant-VAV commented on Examples/TestProject/readme.md
> +Работа проекта проверялась на фрейморке версии 4.7.
Поправил

2021-04-20 06:39 UTC, Ant-VAV commented on Examples/TestProject/ExampleProject/Magic/ChromeDriverFactory.cs
> +        private static readonly string Path = System.IO.Path.GetFullPath(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "..", ".."));
Вынесено в отдельну. папку, в игнор добавлено

2021-04-20 06:39 UTC, Ant-VAV commented on Examples/TestProject/ExampleProject/Magic/ChromeDriverFactory.cs
> +                    var chromeDriverService = CreateChromeDriverService();
Эксперименты со свежими версиями Хрома/Хрома портабл не дали стабильных результатов. Пока решили оставить так.

2021-04-23 10:39 UTC, merged