Первый подход к Ридми
skbkontur/Selone pull request #7
Opened 2021-04-26 13:52 UTC by Ant-VAV

2021-04-26 14:02 UTC, slawwan requested changes

2021-04-26 14:02 UTC, slawwan commented on README.md
> +В директории `Examples\TestProject\ExampleProject` находится тестовый проект, написанный на C#. В нём демонстрируются основные возможности Селона.
сюда бы ссылку сразу добавить, на директорию

2021-04-26 14:02 UTC, slawwan commented on README.md
> +Selone не является ещё одной оболочкой Selenium.WebDriver. Он не оборачивает, не скрывает и не сужает функциональность WebDriver и не запрещает его использование.
и не запрещает его использование -> и не запрещает его использование напрямую

я бы добавил в самый конец слово "напрямую"

2021-04-26 14:02 UTC, slawwan commented on README.md
> +Selone — это библиотека для быстрого запуска собственного набора тестов браузера или поискового робота.
набора браузерных тестов

2021-04-26 14:02 UTC, slawwan commented on README.md
> +В заметке [Быстрый старт](docs/QuickStart.md) описаны основные идеи написания тестов, а так же некоторые шаги. Там же есть пояснения некоторых возможностей Селона.
над этой строкой я бы еще подумал

"некоторые шаги" звучит не очень

2021-04-26 14:12 UTC, Ant-VAV commented on README.md
> +Selone — это библиотека для быстрого запуска собственного набора тестов браузера или поискового робота.
Поправил.

2021-04-26 14:12 UTC, Ant-VAV commented on README.md
> +Selone не является ещё одной оболочкой Selenium.WebDriver. Он не оборачивает, не скрывает и не сужает функциональность WebDriver и не запрещает его использование.
Добавил.

2021-04-26 14:18 UTC, Ant-VAV commented on README.md
> +В директории `Examples\TestProject\ExampleProject` находится тестовый проект, написанный на C#. В нём демонстрируются основные возможности Селона.
Добавил

2021-04-27 06:41 UTC, Ant-VAV commented on README.md
> +В заметке [Быстрый старт](docs/QuickStart.md) описаны основные идеи написания тестов, а так же некоторые шаги. Там же есть пояснения некоторых возможностей Селона.
И тут тоже поправил. Видимо вчера не опубликовал коммент и закрыл вкладку.

2021-04-27 10:55 UTC, slawwan approved these changes

2021-04-27 10:55 UTC, merged